[package]
name = "canvas_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = "0.19.3"
pollster = "*"
futures = "*"
bytemuck = { version = "1.16", features = [ "derive" ] }